-- Generated by Oracle SQL Developer Data Modeler 3.1.3.709
--   at:        2013-04-30 22:44:43 BST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE BigTable 
    ( 
     BigNo NUMBER (7)  NOT NULL , 
     bName VARCHAR2 (30)  NOT NULL , 
     bCompany VARCHAR2 (30)  NOT NULL 
    ) 
;



ALTER TABLE BigTable 
    ADD CONSTRAINT "BigTable PK" PRIMARY KEY ( BigNo ) ;





-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             1
-- CREATE INDEX                             0
-- ALTER TABLE                              1
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
